# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeb00565a4b001a99a52242e5552eb0bc63fe7afa293a790a99403ac81efc950c940601bf55ebdc6593973aee82e4625fec9d39467dc5fe569a0ce5a91bd1edd

test:
  secret_key_base: 60651a32e076f7052d3c1d23103628b2ba309cf7e18a41dfd5239e8ad23a7a32ba77da399d77de1f61df5964e8571e49977400e890a5c957db4583005699babd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
